version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    # rever aula de network por casusa da falha de conexão
  programming-lang-display:
    image: salehkhalil33/programming-lang-display
    depends_on:
      - mongo
    ports:
      - 8080:8080
    environment:
      MONGODB_URL: mongodb://root:root@mongo:27017