version: '3.1'

networks:
  connection:
    driver: bridge

services:
  mongo:
    image: mongo
    restart: always
    networks:
      - connection
  programming-lang-display:
    image: salehkhalil33/programming-lang-display
    depends_on:
      - mongo
    ports:
      - 8080:8080
    environment:
      MONGODB_URL: mongodb://mongo:27017
    networks:
      - connection